version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - uber-net

  db:
    image: postgres:15
    container_name: uber-postgres
    environment:
      POSTGRES_DB: uberApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - uber-net

volumes:
  pgdata:

networks:
  uber-net:
